name: Clip

on:
  workflow_dispatch:
      inputs:
        video_url:
          description: "Video url:"
          required: true
        start_time:
          description: "Clip start time:(hh:mm:ss)"
          required: true
        end_time:
          description: "Clip end time:"
          required: true

permissions:
  contents: read

jobs:
  clip:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp
        chmod +x ./ffmpeg
        cp ./ffmpeg /usr/local/bin
        chmod +x ./ffprobe
        cp ./ffprobe /usr/local/bin
        mkdir output
    - name: Get Clip
      run: |
        python3 ./main.py --url  "${{ github.event.inputs.video_url }}" --start ${{ github.event.inputs.start_time }} --end ${{ github.event.inputs.end_time }}
    - uses: actions/upload-artifact@v3
      with:
        name: output
        path: output
